# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sponsor', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=32)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category1', models.CharField(choices=[('AL', 'Algebra'), ('NT', 'Number Theory'), ('GE', 'Geometry'), ('CO', 'Combinatorics')], max_length=2)),
                ('category2', models.CharField(choices=[('AL', 'Algebra'), ('NT', 'Number Theory'), ('GE', 'Geometry'), ('CO', 'Combinatorics')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.School')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.Team'),
        ),
    ]
