# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20170318_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date_registration_end',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='date_registration_start',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='date_shirt_order_end',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='date_team_add_end',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
    ]
