# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='frontend.Competition'),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
